"""Format a published weekly report as Substack-ready copy for Signal & Noise.

Run by the human after publishing: python -m pipeline.newsletter 2026-W29
Pure text transformation — no network, no Claude calls, and it only accepts
reports that already went through the approval-gated pipeline.publish path.
Substack has no posting API; the final paste stays a human step on purpose.
"""

import sys
from pathlib import Path

from . import config

REPO_URL = "https://github.com/benjaminchoe123/threat-intel-pipeline"

HEADER = """*Signal & Noise separates the threats that matter from the feed noise — a weekly,
plain-English threat report for small orgs and IT generalists, generated by an
[open-source automated pipeline]({repo}) and reviewed by a human before anything ships.*

---

"""

FOOTER = """

---

*How this issue was made: an automated pipeline ingests public threat feeds (CISA KEV,
abuse.ch, and others), Claude enriches each item into a structured analyst note, and a
weekly report is drafted from those notes. A human reviews and approves every issue before
it is published — nothing here is posted unread. The pipeline, its tests, and this week's
full report are public: {repo}.*

**Subscribe for one issue a week, free — if this was useful, that's the whole pitch.**
"""


def build_newsletter(vault_dir, wid):
    """Wrap the published report for `wid` in newsletter boilerplate.

    Reads vault/reports/<wid>.md (published only — drafts are refused so the
    newsletter can never cite something that hasn't passed human review) and
    writes vault/reports/newsletter/<wid>-substack.md.
    """
    vault_dir = Path(vault_dir)
    published = vault_dir / "reports" / f"{wid}.md"
    if not published.exists():
        draft = vault_dir / "reports" / "drafts" / f"{wid}-DRAFT.md"
        if draft.exists():
            raise FileNotFoundError(
                f"{wid} is still a draft — review it and run "
                f"`python -m pipeline.publish {wid}` first"
            )
        raise FileNotFoundError(f"no published report for {wid} at {published}")

    out_dir = vault_dir / "reports" / "newsletter"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"{wid}-substack.md"
    if out.exists():
        raise FileExistsError(f"{out} already exists — refusing to overwrite")

    body = published.read_text(encoding="utf-8")
    out.write_text(
        HEADER.format(repo=REPO_URL) + body + FOOTER.format(repo=REPO_URL),
        encoding="utf-8",
    )
    return out


def main(argv=None):
    argv = argv if argv is not None else sys.argv[1:]
    if len(argv) != 1:
        print("usage: python -m pipeline.newsletter <YYYY-Wnn>")
        return 2
    try:
        out = build_newsletter(config.VAULT_DIR, argv[0])
    except (FileNotFoundError, FileExistsError) as exc:
        print(exc)
        return 1
    print(f"Substack copy ready to paste: {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
